### ISSUE TITLE
Protection remains after sign removal

### ISSUE THREAD

**Issue by Tokoshoran** [Caltinor/DiceMC-Money-Mod#10]
In an oceanblock server, an admin shop was made to allow players to buy and sell their resources to more easily get those they weren't as lucky with, but after removing some of the signage to reorganize things, we found that the protection field was still there. This problem persisted even after a server reboot. Even players with OP permissions couldn't edit those air blocks.

**Comment by Caltinor** [comment]
This sounds like a mod collision.  The mod protections work by checking if the sign data exists and if the player is the owner. If you have destroyed the sign, then MC should have deleted the `BlockEntity` and it's associated data.  The fact that it still exists means something else is saving the block data.
