### ISSUE TITLE
Player can spend money without getting items when they have a full inventory

### ISSUE THREAD

**Issue by henkeeman** [Caltinor/DiceMC-Money-Mod#11]
If you buy from a shop when you have a full inventory, your money gets spent without giving you the items.
I recommend canceling the action and giving the player a prompt when they are trying to buy from the shop without having enough storage left in the inventory.

**Comment by Caltinor** [comment]
Does the shop still lose inventory?

**Comment by henkeeman** [comment]
Yes 👍

**Comment by henkeeman** [comment]
Another option could be just dropping the items that do not fit in the inventory into the game world

**Comment by Caltinor** [comment]
that's how it should work, but there might have been a backend change in MC with the method I use that makes that not the case.  I'll look into it.  what version are you playing with?

**Comment by henkeeman** [comment]
1.18.1 ^^

**Comment by henkeeman** [comment]
So ver: DiceMC Money-1.18-2.0.12.jar

**Comment by Caltinor** [comment]
A new release `1.18-2.0.13` has been released to resolve this issue.  details in https://github.com/Caltinor/DiceMC-Money-Mod/commit/0f6f292146e5ff0590af3bcac4dbb84a0a5c6d32
