### ISSUE TITLE
mod appears to be forge only

### ISSUE THREAD

**Issue by pahanakun** [Caltinor/DiceMC-Money-Mod#13]
Labeling your mod as being for forge would be extremely helpful...

Its confusing what server type your mod is actually for. Its hidden away in the version info for each file, but having it in the title/description would be a great idea. Also linking to the *fabric* version of Flan under your compatible mods section just adds to the confusion.

**Comment by Caltinor** [comment]
The flan link has been updated. Thank you for bringing this to my attention.
