### ISSUE TITLE
SHOPS

### ISSUE THREAD

**Issue by BlazeReflex** [Caltinor/DiceMC-Money-Mod#14]
How do I use shop builder
Whenever I try and make a shop it says "message.activate.failure.money"

**Comment by Caltinor** [comment]
one, you don't have enough funds to pay for what's inside.  second, you don't have the lang files on the client.  either put the mod on the client as well or ensure you have a resource pack with the lang entries on the client.  a resource pack can be found on the CF page for your convenience.

**Comment by BlazeReflex** [comment]
Hello @Caltinor, can I just use shopbuilder instead and how do I use it?

**Comment by Caltinor** [comment]
what is shopbuilder?

**Comment by BlazeReflex** [comment]
when I go on thw world, I can do /shop builder, but I dont know what to type after that

**Comment by Caltinor** [comment]
ah that.  It's a WIP feature.  it is a feature i was working on to allow you to build books without having to type the JSON string manually into a written book.  as of right now it does nothing

**Comment by BlazeReflex** [comment]
I see

**Comment by BlazeReflex** [comment]
Also, I didnt understand your solution on how to build shops, I am on an aternos server

**Comment by Caltinor** [comment]
1. Place a storage block
2. Place a sign on that block
3. Put the shop type on line 1
4. Put the price (without currency symbol or thousands separator) on line 4
5. Put the exact amount you want to trade in the shop
6. Right click the sign to activate the shop
7. Add extra stock to the shop if necessary

**Comment by BlazeReflex** [comment]
> 1. Place a storage block
> 2. Place a sign on that block
> 3. Put the shop type on line 1
> 4. Put the price (without currency symbol or thousands separator) on line 4
> 5. Put the exact amount you want to trade in the shop
> 6. Right click the sign to activate the shop
> 7. Add extra stock to the shop if necessary

Whenever I do that, it says "message.activate.failure.money"! 
How do I fix it when I am on an aternos server and I got this mod through forge on ATERNOS

**Comment by Caltinor** [comment]
Not sure. Aeternos isnt a supported server platform.
