### ISSUE TITLE
Crash after setting the shop in 1.18.1

### ISSUE THREAD

**Issue by Armux14** [Caltinor/DiceMC-Money-Mod#15]
When i right click the sign to set the shop the game crashes.

**Comment by Caltinor** [comment]
crash log please

**Comment by Deffohn** [comment]
[crash-2022-01-25_23.22.55-server.txt](https://github.com/Caltinor/DiceMC-Money-Mod/files/7937608/crash-2022-01-25_23.22.55-server.txt)
crashes on server after right clicking the sign to set the shop.

**Comment by Aerouant28** [comment]
Also having the same issue with a pebblehost server. after right clicking the sign the server crashes but client minecraft is fine.

**Comment by Zuxaw** [comment]
I have exactly the same issue on serve
[crash-2022-01-25_23.11.11-server.txt](https://github.com/Caltinor/DiceMC-Money-Mod/files/7937684/crash-2022-01-25_23.11.11-server.txt)

**Comment by Caltinor** [comment]
Looks like Mojang did some refactoring between 1.18 and 1.18.1, so I'll need to make a special update for that. Thank you all for bringing this to my attention.

**Comment by Zuxaw** [comment]
Thank you so much

**Comment by Caltinor** [comment]
this has been fixed and released on CF
https://www.curseforge.com/minecraft/mc-mods/dicemc-money-mod/files/3624987

Also, the old files have been properly updated to not include 1.18.1 as a valid version
