### ISSUE TITLE
Hi, sign not activating

### ISSUE THREAD

**Issue by venrowbirb** [Caltinor/DiceMC-Money-Mod#17]
Im using this mod for my own smp (server) and when i put the sign stuff on a chest it doesnt activate the sign, turning different colors.
info:
double chest
birch sign

i put:
[server-sell]
1 stack
dirt
$100

and its not activating

**Comment by Caltinor** [comment]
Don't put the `$` on the sign. It gets added automatically when you activate.

**Comment by venrowbirb** [comment]
alright, ill try it! thanks for responding, i playing on this popular server with ecomomy just like this, and i wanted to make my own private one so thx for making this mod

**Comment by venrowbirb** [comment]
ill still leave this open incase it doesnt work

**Comment by venrowbirb** [comment]
![image](https://user-images.githubusercontent.com/101441732/158029943-5c4e52ab-7930-4f26-8d81-9362c29a0d16.png)

**Comment by venrowbirb** [comment]
stil not working and idk why

**Comment by Caltinor** [comment]
There is a server setting that denies users the ability to make signs. If you're on. Server they may have it set to only allow ops to make shops

**Comment by venrowbirb** [comment]
i have op, i own the server
