### ISSUE TITLE
Players are unable to Buy from or Sell to some server shops

### ISSUE THREAD

**Issue by Kenzume** [Caltinor/DiceMC-Money-Mod#18]
Hello, I have been attempting to troubleshoot why my players cant buy from or sell to certain shops. When I admin them, they all work, but when they arent, only some of them do. They are all formatted and set up the same and I cannot figure out what the issue is and why some of them work but others dont

**Comment by Caltinor** [comment]
I've seen this issue before. It's usually a mod collision. Some other mod is prevent the right-click block action. If you have any mods that let you edit signs, that's probably your culprit.

**Comment by Kenzume** [comment]
Thank you, I'll look through them.
