### ISSUE TITLE
only op

### ISSUE THREAD

**Issue by mcbigwin** [Caltinor/DiceMC-Money-Mod#21]
only ops can buy, sell and create shops. non ops cant do anything.

**Comment by Caltinor** [comment]
There's a config setting for that.  Also make sure non-ops are using `[buy]` and `[sell]` in their shops not `[server-buy]` and `[server-sell]`

**Comment by mcbigwin** [comment]
i cant find it

**Comment by Caltinor** [comment]
It's a server config. World/server config/dicemcmm-server.toml

**Comment by mcbigwin** [comment]
what do i chnage

**Comment by mcbigwin** [comment]
it already says

#The minimum permission level to create basic shops.  default= 0 = all players
		#Range: 0 ~ 4
		"shop level" = 0

**Comment by Caltinor** [comment]
Then you have something else causing your non-ops to be unable to use the signs. Try with a fresh forge install and just this mod and see if the issue persists.
