### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Bluemagelord** [Caltinor/DiceMC-Money-Mod#24]
I'm running a 1.18.2 forge-based server on Apex hosting. 

When I installed this mod as part of our modpack the server continued to crash. Once I yanked this mod from the server and restarted it was fine. 

Apex tech support suggests: 

"It looks like the mod is not generating its own configuration files correctly, so you might want to report that as a bug if it doesn't load by itself either. I can't really be 100% certain though."

I have no idea what could have happened but just passing this along. 
-Bluemage.

**Comment by Bluemagelord** [comment]
09.06 15:54:33 [Multicraft] Starting server!
09.06 15:54:33 [Multicraft] Loaded config for "Forge 1.18.2"
09.06 15:54:34 [Multicraft] Updating eula.txt file
09.06 15:54:34 [Server] INFO WARNING: Published ports are discarded when using host network mode
09.06 15:54:34 [Server] INFO 76c60fbd06d101ba57fa4d4a27076201a023899ff1d11c21ffd062f75737c422
09.06 15:54:36 [Server] INFO [Log4jPatcher] [INFO] Transforming org/apache/logging/log4j/core/pattern/MessagePatternConverter
09.06 15:54:36 [Server] INFO [Log4jPatcher] [WARN]  Unable to find noLookups:Z field in org/apache/logging/log4j/core/pattern/MessagePatternConverter
09.06 15:54:36 [Server] INFO [Log4jPatcher] [INFO] Transforming org/apache/logging/log4j/core/lookup/JndiLookup
09.06 15:54:37 [Server] INFO 2022-06-09 15:54:37,054 main WARN Advanced terminal features are not available in this environment
09.06 15:54:37 [Server] main/INFO [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 40.1.48, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914, nogui]
09.06 15:54:37 [Server] main/INFO [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.1 by Red Hat, Inc.
09.06 15:54:37 [Server] main/INFO [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/jar/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=SERVER
09.06 15:54:37 [Server] INFO Exception in thread "main" com.electronwill.nightconfig.core.io.ParsingException: Not enough data available
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ParsingException.notEnoughData(ParsingException.java:22)
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ReaderInput.directReadChar(ReaderInput.java:36)
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.AbstractInput.readChar(AbstractInput.java:49)
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.StringParser.parseBasic(StringParser.java:23)
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:45)
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:69)
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:57)
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:72)
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37)
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113)
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219)
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202)
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.WriteAsyncFileConfig.load(WriteAsyncFileConfig.java:138)
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.48/net.minecraftforge.fml.loading.moddiscovery.ModFileParser.modsTomlParser(ModFileParser.java:44)
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.48/net.minecraftforge.fml.loading.moddiscovery.ModFileParser.readModList(ModFileParser.java:31)
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.48/net.minecraftforge.fml.loading.moddiscovery.ModFile.identifyMods(ModFile.java:105)
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.48/net.minecraftforge.fml.loading.moddiscovery.ModValidator.validateFiles(ModValidator.java:54)
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.48/net.minecraftforge.fml.loading.moddiscovery.ModValidator.stage1Validation(ModValidator.java:43)
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.48/net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:62)
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.48/net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:166)
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.48/net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:86)
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112)
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:100)
09.06 15:54:37 [Server] INFO at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
09.06 15:54:37 [Server] INFO at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
09.06 15:54:37 [Server] INFO at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
09.06 15:54:37 [Server] INFO at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
09.06 15:54:37 [Server] INFO at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
09.06 15:54:37 [Server] INFO at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
09.06 15:54:37 [Server] INFO at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
09.06 15:54:37 [Server] INFO at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
09.06 15:54:37 [Server] INFO at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:102)
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:55)
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:87)
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
09.06 15:54:37 [Server] INFO at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
09.06 15:54:37 [Server] INFO at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
09.06 15:54:39 [Multicraft] Server shut down (starting)
09.06 15:54:39 [Multicraft] Restarting crashed server in 300 seconds
09.06 15:54:39 [Multicraft] Server stopped

**Comment by Bluemagelord** [comment]
There ya go bud. Your mod would have been PERFECT for our server so I hope this is something easily fixed. But I had to recreate the error (loading the mod to the server and then try to reboot - which caused the error again) to get you the text. Hope this helps

**Comment by Caltinor** [comment]
could you try going using the second most recent version?  I'm wondering if the last PR I merged did something funky to the mod.

**Comment by Bluemagelord** [comment]
I’ll try that in a sec. Some of my players reported that adding the mod to their mod pack profile crashed their game on launch

**Comment by Caltinor** [comment]
I believe I found the issue, and it was with the last PR that was pushed.  The last version just added a compat feature, so unless you are using Section Protection as a mod, you can go back one version and be fine.
