### ISSUE TITLE
its broken

### ISSUE THREAD

**Issue by MEME-KING16** [Caltinor/DiceMC-Money-Mod#33]
![2022-10-09_13 52 06](https://user-images.githubusercontent.com/115302822/194771974-c56a6502-1135-43bc-965c-2bb3406071e3.png)
![2022-10-09_13 52 19](https://user-images.githubusercontent.com/115302822/194771978-51f8ac8a-a741-4121-9bd2-5b73326ea155.png)
![2022-10-09_13 52 21](https://user-images.githubusercontent.com/115302822/194771982-692748a0-beb9-48a5-9ce8-fa04e78717f4.png)
![2022-10-09_13 52 23](https://user-images.githubusercontent.com/115302822/194771985-beae8747-3ad5-4e44-a949-12fb
![2022-10-09_13 52 25](https://user-images.githubusercontent.com/115302822/194771989-eb5ea7c7-943b-401f-8d22-1ce5965497d5.png)
c045a199.png)
![2022-10-09_13 52 27](https://user-images.githubusercontent.com/115302822/194771991-3ca2f27d-f01a-4258-a85d-cde1277625ac.png)
![2022-10-09_13 52 29](https://user-images.githubusercontent.com/115302822/194771996-40f304c9-b8ce-4d58-975b-c51ce97253a8.png)
![2022-10-09_13 52 32](https://user-images.githubusercontent.com/115302822/194771999-40bbdc32-c826-4b5a-aa8a-fe069fd9c6a7.png)

**Comment by Caltinor** [comment]
the message in the last picture literally tells you the problem.  you cannot have symbols in your sign.

**Comment by Caltinor** [comment]
also, price goes on the 4th line

**Comment by MEME-KING16** [comment]
ok thanks
