### ISSUE TITLE
[Suggestion] Toggleable chestshop protection

### ISSUE THREAD

**Issue by JustAnotherGhostName** [Caltinor/DiceMC-Money-Mod#37]
Ideally a player should be able to do /toggleShopProtection which would toggle on or off the protection of their own shops so that they could place blocks / items next to the chest shop without it being deleted.

**Comment by Caltinor** [comment]
The protections only affect the 6 blocks around the shop block. The intended behavior is for players to make their block placements/connections in advance, then activate their shop.

**Comment by JustAnotherGhostName** [comment]
I figured as much, but it takes a bit of time when players dont do it in advance and then say want to place a bunch of pipes or exporters from other mods to autofill the chests. The protection is a good feature to have, but I dont think it should also restrict the chestshop owner since it can take a lot of time to fix the mistake. 

Not only that, but what if they want to change how it works at a later date? Start off with a manually filled chest, then move towards auto filling them.

**Comment by Caltinor** [comment]
I could probably add an owner exception.  That should be simple enough

**Comment by JustAnotherGhostName** [comment]
That sounds good. Thank you for your work and quick responses.
