### ISSUE TITLE
FML error with latest FTB mods

### ISSUE THREAD

**Issue by Ki-Tan2934** [Caltinor/DiceMC-Money-Mod#5]
The title says it all
https://pastebin.com/PZ62bs0f

**Comment by Caltinor** [comment]
Should be fixed as of f5b3cd953f5ad0515a6721e9e9303446d34ce228
Newest version: https://www.curseforge.com/minecraft/mc-mods/dicemc-money-mod/files/3459751

the odd thing was, I never got your specific error and was able to load the game.  I did have to update Quests, Lib, and Teams, but after doing that everything worked fine.  So here's hoping it works for you.
