### ISSUE TITLE
Sell shops only take a max of one stack

### ISSUE THREAD

**Issue by Charmanth** [Caltinor/DiceMC-Money-Mod#6]
Hi, I'm running a server for friends, and there seems to be either a bug or a bit of missing information.  Sell shops will only take one full stack of an item no matter what is in the chest at the time of activation.

Steps to reproduce:
--Set up a server sell shop (Have not tested this with player sell shops)
--Chest has 2 stacks of the same item (full stacks)
--Activate shop with the 2 stacks in the chest,
--Sell to shop.  Print out will be "correct" but the amount taken from your inventory is not. (takes 64 instead of 128).
--??????
--Profit 

As the mod page doesn't say anything about capping items to a full stack in the chest, I'm assuming this is a bug.

**Comment by Charmanth** [comment]
Version of the mod is 2.0.10, forgot to include that

**Comment by Caltinor** [comment]
this would definitely be a bug.  i'll look into that now.

**Comment by Caltinor** [comment]
which version of MC 1.16 or 1.17?

**Comment by Charmanth** [comment]
1.16 for MC.

**Comment by Caltinor** [comment]
this has been fixed in both 1.16 and 1.17 versions.   Reference mod version 2.0.11
