### ISSUE TITLE
Quark sign edit feature messes up shop signs

### ISSUE THREAD

**Issue by Garagoth** [Caltinor/DiceMC-Money-Mod#7]
Righ-click on sign in Quark allows to edit sign.

It still works as shop, but every shop operation brings up sign editing.

**Comment by Caltinor** [comment]
I think I have a solution to fix this though.  Let me test an idea and i'll keep you both posted.

**Comment by Garagoth** [comment]
Shift+right click with bsre hand removes sign.

**Comment by Caltinor** [comment]
Fixed in 1.16 f65517ddf50d7782f76c3bbd076851b7641e8d17
and 1.17 71aee44aceb27a7247bb9cdce6525129b88aec1f (though I know quark isn't on 1.17 yet, the fix works in advance)

**Comment by Caltinor** [comment]
1.17 isn't pushed to CF yet.  need to tweak a couple other things first.
