### ISSUE TITLE
Bug with Auto Chisel block from Chisel mod

### ISSUE THREAD

**Issue by gdharron** [Caltinor/DiceMC-Money-Mod#9]
Had a very strange event take place tonight on my Oceanblock server, player placed an auto chisel block and somehow it caused any and all dropped items to immediately disappear and be deleted. Maybe a Chisel bug but the reason I wanted to submit this is that the error in the console also mentions your mod, I'm not a java expert so couldn't quite tell if it is caused by your mod per se or just a coincidence. 

https://pastebin.com/5jY9h8WZ

**Comment by gdharron** [comment]
Update: tested auto chisel in SP and it works as intended its seems to be an issue with your mod somehow. there wasn't a sign on it or anything like that just 2x auto chisel side by side and it cause that error in console and all items to delete after being dropped. If you need more info let me know, thanks

**Comment by Caltinor** [comment]
Do you have the whole log?  That's just showing all the event handlers your pack triggers when blocks are right clicked. Also, you said there was no sign on the chests?

**Comment by gdharron** [comment]
Finally got a crash report for you:
https://pastebin.com/BKTD1abH

From tonight after trying to remove the auto chisel with a builder

**Comment by Caltinor** [comment]
Have you run this by team chisel? The money mod doesn't create ticking entities.  Also, MCJty's RF tools mod is in that stack trace too.  Have you tried removing that mod to see if the issue is from there?

The lines of code in money mod, where the error is happening, is a safety check, so I'd be surprised if that was where the issue is.

**Comment by gdharron** [comment]
I agree it's actually a chisel issue, I'll make a bug report for them too. yeah, RFTools is in there cause I used a builder to try and remove the auto chisel lmao game didn't like that. Thanks for your time.
